import { mkdir } from 'node:fs/promises';
import { chromium } from 'playwright';

const url = process.env.GAME_URL ?? 'http://127.0.0.1:5173/';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on('pageerror', (error) => errors.push(error.message));
page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()); });

try {
  await mkdir('artifacts', { recursive: true });
  await page.goto(url);
  await page.getByText('Связь есть').waitFor();
  await page.locator('.cues').getByRole('button', { name: 'Поговорить с пассажиром' }).click();
  await page.locator('.details').getByText('Алексей').waitFor();
  const approachDocument = page.getByRole('button', { name: 'Подойти', exact: true });
  if (await approachDocument.count()) await approachDocument.click();
  await page.getByRole('button', { name: 'Поговорить', exact: true }).waitFor({ timeout: 10000 });
  await page.getByRole('button', { name: 'Поговорить', exact: true }).click();
  await page.getByText('Удостоверение', { exact: true }).waitFor();
  await page.getByText('Билет', { exact: true }).waitFor();
  await page.screenshot({ path: 'artifacts/document-comparison.png' });
  await page.getByRole('button', { name: 'Сверить и допустить' }).click();
  await page.getByText('Документы сверены. Пассажир допущен', { exact: false }).waitFor();
  await page.getByRole('button', { name: '×3' }).click();
  await page.getByText('В вагоне слышен слабый свист.', { exact: false }).waitFor({ timeout: 10000 });
  await page.getByRole('button', { name: 'Пауза' }).click();
  await page.locator('.cues').getByRole('button', { name: 'Поговорить с пассажиром' }).click();
  await page.getByRole('button', { name: 'Поговорить', exact: true }).waitFor({ timeout: 15000 });
  await page.getByRole('button', { name: 'Поговорить', exact: true }).click();
  await page.getByRole('button', { name: 'Уточнить симптомы' }).click();
  await page.getByText('Заложило уши, и справа слышен свист.', { exact: false }).waitFor();
  await page.getByRole('button', { name: 'Проверить панель' }).click();
  await page.locator('.cues').getByRole('button', { name: 'Подойти к признаку' }).click();
  await page.getByRole('button', { name: 'Подробный осмотр' }).waitFor({ timeout: 15000 });
  await page.screenshot({ path: 'artifacts/pressure-selected.png' });
  await page.getByRole('button', { name: 'Быстрый осмотр' }).click();
  await page.locator('.observation').getByText('Есть отклонение показания.').waitFor();
  await page.getByRole('button', { name: 'Подробный осмотр' }).click();
  await page.getByRole('button', { name: 'Доложить о показании' }).click();
  await page.getByRole('button', { name: 'Показать итог смены' }).click();
  await page.getByText('Смена завершена', { exact: true }).waitFor();
  await page.screenshot({ path: 'artifacts/pressure-success.png' });
  console.log('pressure:', await page.locator('.details').innerText());

  await page.getByRole('button', { name: 'Пожар', exact: true }).click();
  await page.getByRole('button', { name: '×3' }).click();
  await page.locator('.cues').getByText('Появился дым!').waitFor({ timeout: 10000 });
  await page.getByRole('button', { name: 'Пауза' }).click();
  await page.getByRole('button', { name: 'Подойти к огнетушителю' }).click();
  await page.getByRole('button', { name: 'Взять огнетушитель' }).waitFor({ timeout: 15000 });
  await page.getByRole('button', { name: 'Взять огнетушитель' }).click();
  await page.getByRole('button', { name: 'Подготовить огнетушитель' }).click();
  await page.getByRole('button', { name: 'Подойти к очагу' }).click();
  await page.getByRole('button', { name: 'Применить огнетушитель' }).waitFor({ timeout: 15000 });
  await page.getByRole('button', { name: 'Применить огнетушитель' }).click();
  await page.getByRole('button', { name: 'Показать итог смены' }).click();
  await page.getByText('Очаг потушен.', { exact: false }).first().waitFor();
  await page.screenshot({ path: 'artifacts/fire-success.png' });
  console.log('fire success:', await page.locator('.details').innerText());

  await page.getByRole('button', { name: 'Пожар', exact: true }).click();
  await page.getByRole('button', { name: '×3' }).click();
  await page.locator('.cues').getByText('Пламя усиливается!').waitFor({ timeout: 15000 });
  await page.getByRole('button', { name: 'Показать итог смены' }).click();
  await page.getByText('Очаг остался активным.').waitFor();
  await page.screenshot({ path: 'artifacts/fire-failure.png' });
  console.log('fire failure:', await page.locator('.details').innerText());

  await page.getByRole('button', { name: 'Сервис', exact: true }).click();
  await page.getByRole('button', { name: '×3' }).click();
  await page.getByText('Помочь с грязным местом').waitFor({ timeout: 10000 });
  await page.getByRole('button', { name: 'Пауза' }).click();
  await page.getByRole('button', { name: 'Поговорить с пассажиром' }).click();
  await page.getByRole('button', { name: 'Поговорить', exact: true }).waitFor({ timeout: 15000 });
  await page.getByRole('button', { name: 'Поговорить', exact: true }).click();
  await page.getByRole('button', { name: 'Уточнить проблему' }).click();
  await page.getByRole('button', { name: 'Проверить место и помочь' }).click();
  await page.getByRole('button', { name: 'Подойти к цели' }).click();
  await page.getByRole('button', { name: 'Завершить задачу' }).waitFor({ state: 'visible', timeout: 10000 });
  await page.getByRole('button', { name: 'Завершить задачу' }).click();
  await page.getByRole('button', { name: 'Показать итог смены' }).click();
  await page.screenshot({ path: 'artifacts/service-success.png' });
  console.log('service:', await page.locator('.details').innerText());

  await page.getByRole('button', { name: 'Конфликт', exact: true }).click();
  await page.getByRole('button', { name: '×3' }).click();
  await page.getByText('Разрешить спор о месте').waitFor({ timeout: 10000 });
  await page.getByRole('button', { name: 'Пауза' }).click();
  await page.getByRole('button', { name: 'Поговорить с пассажиром' }).click();
  await page.getByRole('button', { name: 'Поговорить', exact: true }).waitFor({ timeout: 15000 });
  await page.getByRole('button', { name: 'Поговорить', exact: true }).click();
  await page.getByRole('button', { name: 'Выслушать обстоятельства' }).click();
  await page.getByRole('button', { name: 'Спокойно сверить билеты' }).click();
  await page.getByRole('button', { name: 'Показать итог смены' }).click();
  await page.screenshot({ path: 'artifacts/conflict-success.png' });
  console.log('conflict:', await page.locator('.details').innerText());
  await page.getByRole('button', { name: 'Проверить связь' }).click();
  await page.getByText('Переподключение').waitFor({ timeout: 5000 });
  await page.getByText('Связь есть').waitFor({ timeout: 10000 });
  await page.getByText('Смена завершена', { exact: true }).waitFor();
  console.log('reconnect: restored debrief');

  await page.getByRole('button', { name: 'Сервис', exact: true }).click();
  await page.getByRole('button', { name: '×3' }).click();
  await page.getByText('Помочь с грязным местом').waitFor({ timeout: 10000 });
  await page.getByRole('button', { name: 'Пауза' }).click();
  await page.getByRole('button', { name: 'Поговорить с пассажиром' }).click();
  await page.getByRole('button', { name: 'Поговорить', exact: true }).waitFor({ timeout: 15000 });
  await page.getByRole('button', { name: 'Поговорить', exact: true }).click();
  await page.getByRole('button', { name: 'Уточнить проблему' }).waitFor();
  await page.getByRole('button', { name: 'Давление', exact: true }).click();
  await page.getByText('Активных запросов нет.').waitFor();
  await page.waitForFunction(() => document.querySelector('.dialogue')?.textContent === '');
  console.log('restart: old task and dialogue cleared');
  if (errors.length > 0) throw new Error(errors.join('\n'));
} finally {
  await browser.close();
}
