// Синтетические данные для демо-стенда. Реальных ФИО и ПДН нет: сотрудники
// обозначены позывными. Даты считаются от текущего момента, чтобы стенд не
// «старел». Заменяется ответами сервера, когда появится API.

import { formatDate } from './format';
import type {
  Achievement,
  Leaderboard,
  NextShift,
  Notice,
  Profile,
  Run,
  Scope,
  Stats,
} from './model';

const HOUR = 60 * 60 * 1000;
const at = (hoursFromNow: number) => new Date(Date.now() + hoursFromNow * HOUR).toISOString();
const daysAgo = (days: number) => at(-days * 24);
const expiresAt = at(3 * 24);

export const profile: Profile = {
  callsign: 'A7F3',
  position: 'Проводник бизнес-класса',
  brigade: '12',
  depot: 'Москва',
  level: 7,
  points: 2340,
  levelFrom: 2000,
  levelTo: 3000,
  streakDays: 6,
  expiring: { points: 120, at: expiresAt },
  competencies: {
    safety: 81,
    procedure: 74,
    detection: 58,
    reaction: 66,
    service: 79,
    escalation: 43,
  },
  trend: {
    safety: 4,
    procedure: 2,
    detection: 9,
    reaction: -3,
    service: 1,
    escalation: -6,
  },
  weakNote: {
    escalation: 'В 3 из 5 последних рейсов доклад начальнику поезда ушёл позже жалобы пассажира.',
    detection: 'Растёт: две неисправности найдены детальным осмотром на приёмке.',
  },
};

export const stats: Stats = {
  runs: 38,
  completed: 31,
  incidents: 5,
  terminated: 2,
  defectsFound: 54,
  missedChecks: 17,
  avgReactionSec: 7.4,
  escalationsCorrect: 23,
  escalationsTotal: 31,
  luckyViolations: 9,
};

export const nextShift: NextShift = {
  train: 'ВСМ 707',
  from: 'Москва',
  fromGenitive: 'Москвы',
  to: 'Санкт-Петербург',
  car: 4,
  carClass: 'Бизнес',
  departure: '09:30',
  stops: ['Тверь', 'Бологое'],
  focus: ['escalation', 'detection'],
};

export const runs: Run[] = [
  {
    id: 'r412',
    train: 'ВСМ 703',
    route: 'Москва → Санкт-Петербург',
    car: 4,
    carClass: 'Бизнес',
    finishedAt: daysAgo(1),
    playMinutes: 38,
    outcome: 'completed',
    outcomeNote: 'Две ситуации предотвращены',
    loyalty: 72,
    safety: 88,
    points: 184,
    competencyDelta: { detection: 4, escalation: 2, service: 3, reaction: -1 },
    facts: { prevented: 2, incidents: 0, complaints: 0, interventions: 0 },
    decisions: [
      {
        id: 'd1',
        time: '08:41',
        stage: 'acceptance',
        situation: 'Огнетушитель в тамбуре: сорвана пломба',
        action: 'Осмотрел и доложил начальнику поезда до посадки',
        verdict: 'best',
        loyalty: 0,
        safety: 10,
      },
      {
        id: 'd2',
        time: '08:52',
        stage: 'acceptance',
        situation: 'Дверь 2: индикатор мигает, видно только при детальном осмотре',
        action: 'Дверь 2 подробно не осматривал',
        verdict: 'missed',
        loyalty: 0,
        safety: -8,
        consequence: 'В Твери дверь закрылась со второй попытки. Задержки не было.',
        lucky: true,
        better: 'Детально осмотреть обе двери до начала посадки — это около 35 игровых секунд.',
        basis: 'Приёмка вагона: проверка дверей и средств эвакуации',
      },
      {
        id: 'd3',
        time: '09:07',
        stage: 'boarding',
        situation: 'Пассажир с билетом на завтрашний рейс',
        action: 'Сверил дату, не пустил в вагон, объяснил, где переоформить',
        verdict: 'best',
        loyalty: 2,
        safety: 4,
        reactionSec: 12,
      },
      {
        id: 'd4',
        time: '09:34',
        stage: 'enroute',
        situation: 'Пассажиру в 6-м ряду закладывает уши, у окна слышен свист',
        action: 'Опросил соседних пассажиров, затем доложил',
        verdict: 'ok',
        loyalty: 3,
        safety: 6,
        reactionSec: 41,
        better:
          'Докладывать сразу: свист и жалобы на уши — признак нарушения герметичности. Опрос можно провести после доклада.',
        basis: 'Эскалация технических отклонений',
      },
      {
        id: 'd5',
        time: '09:58',
        stage: 'enroute',
        situation: 'Два пассажира спорят за место у окна',
        action: 'Проверил билеты, рассадил по местам, предложил свободное место у окна',
        verdict: 'best',
        loyalty: 8,
        safety: 0,
        reactionSec: 20,
      },
      {
        id: 'd6',
        time: '10:21',
        stage: 'handover',
        situation: 'Финальный обход: сумка под креслом в 3-м ряду',
        action: 'Передал дежурному и указал в докладе о сдаче вагона',
        verdict: 'best',
        loyalty: 0,
        safety: 2,
      },
    ],
  },
  {
    id: 'r409',
    train: 'ВСМ 712',
    route: 'Санкт-Петербург → Москва',
    car: 2,
    carClass: 'Эконом',
    finishedAt: daysAgo(2),
    playMinutes: 44,
    outcome: 'incident',
    outcomeNote: 'Повторное срабатывание датчика дыма',
    loyalty: 54,
    safety: 61,
    points: 96,
    competencyDelta: { escalation: -4, procedure: -2, service: 2 },
    facts: { prevented: 0, incidents: 1, complaints: 2, interventions: 1 },
    decisions: [
      {
        id: 'd1',
        time: '12:48',
        stage: 'acceptance',
        situation: 'Аптечка: не хватает бинтов',
        action: 'Аптечку не открывал',
        verdict: 'missed',
        loyalty: 0,
        safety: -6,
        consequence: 'В 13:40 бинт понадобился — пришлось идти в вагон 3, ушло две минуты.',
        better: 'Проверить комплектность аптечки на приёмке и доложить о недостаче.',
        basis: 'Приёмка вагона: медицинская аптечка',
      },
      {
        id: 'd2',
        time: '13:40',
        stage: 'enroute',
        situation: 'Пассажир порезал руку о разбитый стакан',
        action: 'Принёс аптечку из вагона 3, обработал порез, доложил',
        verdict: 'ok',
        loyalty: 4,
        safety: 4,
        reactionSec: 128,
      },
      {
        id: 'd3',
        time: '14:02',
        stage: 'enroute',
        situation: 'В туалете курят электронную сигарету',
        action: 'Сделал замечание, начальнику поезда не докладывал',
        verdict: 'worse',
        loyalty: 1,
        safety: -5,
        consequence: 'В 14:26 пассажир закурил снова, сработал датчик дыма.',
        better: 'Замечание и доклад начальнику поезда: решение о повторном нарушении — за ним.',
        basis: 'Эскалация нарушений правил проезда',
      },
      {
        id: 'd4',
        time: '14:26',
        stage: 'enroute',
        situation: 'Сработал датчик дыма в туалете',
        action: 'Пришёл через 40 секунд, осмотрел, доложил',
        verdict: 'ok',
        loyalty: -6,
        safety: 2,
        reactionSec: 40,
      },
    ],
  },
  {
    id: 'r405',
    train: 'ВСМ 701',
    route: 'Москва → Санкт-Петербург',
    car: 4,
    carClass: 'Бизнес',
    finishedAt: daysAgo(4),
    playMinutes: 35,
    outcome: 'completed',
    outcomeNote: 'Табло аварийного выхода найдено на приёмке',
    loyalty: 80,
    safety: 91,
    points: 210,
    competencyDelta: { detection: 5, safety: 3 },
    facts: { prevented: 1, incidents: 0, complaints: 0, interventions: 0 },
    decisions: [
      {
        id: 'd1',
        time: '08:37',
        stage: 'acceptance',
        situation: 'Табло аварийного выхода не светится',
        action: 'Нашёл при детальном осмотре салона, доложил',
        verdict: 'best',
        loyalty: 0,
        safety: 12,
      },
      {
        id: 'd2',
        time: '09:49',
        stage: 'enroute',
        situation: 'Пассажирке душно, просит открыть окно',
        action: 'Объяснил, что окна не открываются, сообщил о температуре, принёс воду',
        verdict: 'best',
        loyalty: 7,
        safety: 0,
        reactionSec: 15,
      },
    ],
  },
  {
    id: 'r401',
    train: 'ВСМ 710',
    route: 'Санкт-Петербург → Москва',
    car: 6,
    carClass: 'Эконом',
    finishedAt: daysAgo(6),
    playMinutes: 22,
    outcome: 'terminated',
    outcomeNote: 'Нарушение герметичности вагона',
    loyalty: 38,
    safety: 22,
    points: 20,
    competencyDelta: { escalation: -8, detection: -3 },
    facts: { prevented: 0, incidents: 1, complaints: 4, interventions: 2 },
    decisions: [
      {
        id: 'd1',
        time: '15:12',
        stage: 'enroute',
        situation: 'Двое пассажиров жалуются, что закладывает уши',
        action: 'Предложил воды, не докладывал',
        verdict: 'missed',
        loyalty: 2,
        safety: -20,
        consequence: 'К 15:30 свист стал слышен во всём салоне, поезд снизил скорость.',
        better: 'Жалобы на уши — косвенный признак нарушения герметичности. Докладывать сразу.',
        basis: 'Эскалация технических отклонений',
      },
      {
        id: 'd2',
        time: '15:30',
        stage: 'enroute',
        situation: 'Бортинженер пришёл в вагон по вызову соседнего проводника',
        action: 'Не смог сказать, когда начались жалобы',
        verdict: 'worse',
        loyalty: -4,
        safety: -10,
        better: 'Фиксировать время первых признаков: это первое, что спросят при разборе.',
      },
    ],
  },
  {
    id: 'r398',
    train: 'ВСМ 705',
    route: 'Москва → Санкт-Петербург',
    car: 3,
    carClass: 'Эконом',
    finishedAt: daysAgo(8),
    playMinutes: 41,
    outcome: 'completed',
    outcomeNote: 'Доехали, но с жалобой на обслуживание',
    loyalty: 69,
    safety: 77,
    points: 150,
    competencyDelta: { service: 2, reaction: 2 },
    facts: { prevented: 1, incidents: 0, complaints: 1, interventions: 0 },
    decisions: [
      {
        id: 'd1',
        time: '09:15',
        stage: 'boarding',
        situation: 'Пассажир с собакой без переноски',
        action: 'Попросил подождать в стороне, продолжил посадку, потом разобрался',
        verdict: 'best',
        loyalty: 3,
        safety: 5,
        reactionSec: 9,
      },
      {
        id: 'd2',
        time: '10:05',
        stage: 'stop',
        situation: 'Бологое: пассажир не успевает выйти с багажом',
        action: 'Помог вынести чемодан, двери закрыли по графику',
        verdict: 'best',
        loyalty: 6,
        safety: 2,
        reactionSec: 6,
      },
      {
        id: 'd3',
        time: '10:40',
        stage: 'enroute',
        situation: 'Пассажир просит сменить место из-за шумных соседей',
        action: 'Отказал: свободных мест нет',
        verdict: 'worse',
        loyalty: -7,
        safety: 0,
        consequence: 'Пассажир оставил жалобу на обслуживание.',
        better: 'Проверить свободные места в соседних вагонах и поговорить с соседями.',
      },
    ],
  },
];

export const achievements: Achievement[] = [
  {
    code: 'before-boarding',
    title: 'До посадки',
    description: 'Найти неисправность на приёмке, до начала посадки',
    earnedAt: daysAgo(4),
  },
  {
    code: 'before-complaint',
    title: 'Раньше жалобы',
    description: 'Заметить проблему до того, как о ней скажет пассажир',
    earnedAt: daysAgo(9),
  },
  {
    code: 'clean-sweep',
    title: 'Чистый обход',
    description: 'Завершить рейс без пропущенных обязательных проверок',
    earnedAt: daysAgo(12),
  },
  {
    code: 'first-aid',
    title: 'Первая помощь',
    description: 'Помочь пассажиру и доложить, не отходя от регламента',
    earnedAt: daysAgo(15),
  },
  {
    code: 'cold-head',
    title: 'Холодная голова',
    description: 'Пять критических решений быстрее половины отведённого времени',
    earnedAt: daysAgo(20),
  },
  {
    code: 'streak',
    title: 'Неделя в строю',
    description: 'Семь дней подряд хотя бы один рейс',
    earnedAt: null,
    progress: { value: 6, total: 7 },
  },
  {
    code: 'pressure',
    title: 'Уши заложило',
    description: 'Распознать признаки нарушения герметичности и доложить сразу',
    earnedAt: null,
  },
  {
    code: 'detail',
    title: 'Под лупой',
    description: 'Найти пять неисправностей, видных только при детальном осмотре',
    earnedAt: null,
    progress: { value: 2, total: 5 },
  },
  {
    code: 'three-calls',
    title: 'Три обращения',
    description: 'Правильно разобрать три одновременных обращения пассажиров',
    earnedAt: null,
  },
  {
    code: 'rare',
    title: 'Редкий случай',
    description: 'Справиться с событием, которое большинство проводников пропускает',
    earnedAt: null,
  },
];

export const leaderboards: Record<Scope, Leaderboard> = {
  brigade: {
    season: 'Сезон 39',
    endsAt: at(3 * 24),
    total: 8,
    rows: [
      { rank: 1, callsign: 'K2D9', points: 1910, move: 0 },
      { rank: 2, callsign: 'Q81B', points: 1655, move: 1 },
      { rank: 3, callsign: 'A7F3', points: 1240, move: 2, me: true },
      { rank: 4, callsign: 'M0C4', points: 1190, move: -2 },
      { rank: 5, callsign: 'Z7E2', points: 980, move: -1 },
      { rank: 6, callsign: 'T4A1', points: 860, move: 0 },
      { rank: 7, callsign: 'R9F0', points: 610, move: 0 },
      { rank: 8, callsign: 'B3C7', points: 420, move: 0 },
    ],
  },
  depot: {
    season: 'Сезон 39',
    endsAt: at(3 * 24),
    total: 96,
    rows: [
      { rank: 1, callsign: 'H6E2', points: 2480, move: 0 },
      { rank: 2, callsign: 'K2D9', points: 1910, move: 3 },
      { rank: 3, callsign: 'P5B8', points: 1870, move: -1 },
      { rank: 4, callsign: 'W1D3', points: 1790, move: -1 },
      { rank: 5, callsign: 'Q81B', points: 1655, move: 2 },
      { rank: 11, callsign: 'A7F3', points: 1240, move: 4, me: true },
    ],
  },
  company: {
    season: 'Сезон 39',
    endsAt: at(3 * 24),
    total: 1380,
    rows: [
      { rank: 1, callsign: 'N8A5', points: 3120, move: 0 },
      { rank: 2, callsign: 'F2C6', points: 2950, move: 1 },
      { rank: 3, callsign: 'H6E2', points: 2480, move: -1 },
      { rank: 4, callsign: 'L0B4', points: 2390, move: 0 },
      { rank: 5, callsign: 'Y7D1', points: 2210, move: 5 },
      { rank: 214, callsign: 'A7F3', points: 1240, move: 31, me: true },
    ],
  },
};

/** Место бригады среди бригад депо. */
export const brigadeInDepot = { rank: 2, total: 14 };

export const notices: Notice[] = [
  {
    id: 'n1',
    kind: 'expiring',
    title: `120 баллов спишутся ${formatDate(expiresAt)}`,
    text: 'Баллы сохранятся, если до этой даты пройти хотя бы один рейс.',
    at: at(-2),
    unread: true,
  },
  {
    id: 'n2',
    kind: 'advice',
    title: 'Эскалация ниже среднего по депо',
    text: '43 из 100 при среднем 61. В следующем рейсе будет техническая неисправность, о которой нужно доложить.',
    at: at(-5),
    unread: true,
  },
  {
    id: 'n3',
    kind: 'scenario',
    title: 'Добавлены две ситуации',
    text: 'Задымление в тамбуре и пассажир без билета на промежуточной станции.',
    at: daysAgo(1),
    unread: true,
  },
  {
    id: 'n4',
    kind: 'challenge',
    title: 'Неделя своевременных докладов',
    text: 'Бригады депо соревнуются до воскресенья. Бригада 12 идёт второй из 14.',
    at: daysAgo(2),
    unread: false,
  },
  {
    id: 'n5',
    kind: 'overtaken',
    title: '#Q81B поднялся на 2-е место в бригаде',
    text: 'Вы на 3-м месте, разница 415 баллов.',
    at: daysAgo(3),
    unread: false,
  },
  {
    id: 'n6',
    kind: 'achievement',
    title: 'Получен знак «До посадки»',
    text: 'Табло аварийного выхода найдено на приёмке, рейс ВСМ 701.',
    at: daysAgo(4),
    unread: false,
    link: '#/runs/r405',
  },
];
